apiVersion: apps/v1
kind: Deployment
metadata:
  name: barracuda-thruster-output-controller
  labels:
    app: barracuda-thruster-output-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: barracuda-thruster-output-controller
  template:
    metadata:
      labels:
        app: barracuda-thruster-output-controller
    spec:
      nodeSelector:
        kubefamily: raspberrypi
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: barracuda-thruster-output-controller
          image: ghcr.io/usc-robosub/barracuda-thruster-output-controller:latest
          command: ["/bin/bash", "/opt/barracuda-thruster-output-controller/entrypoint.sh"]
          env:
            - name: ROS_MASTER_URI
              value: "http://barracuda-description.default.svc.cluster.local:11311"
            - name: ROS_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          tty: true
          securityContext:
            runAsUser: 0
      restartPolicy: Always
