apiVersion: apps/v1
kind: Deployment
metadata:
  name: barracuda-vision
  labels:
    app: barracuda-vision
spec:
  replicas: 1
  selector:
    matchLabels:
      app: barracuda-vision
  template:
    metadata:
      labels:
        app: barracuda-vision
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: barracuda-vision
          image: ghcr.io/usc-robosub/barracuda-vision:latest
          imagePullPolicy: Always
          command: ["/bin/bash", "/opt/barracuda-vision/entrypoint.sh"]
          env:
            - name: ROS_MASTER_URI
              value: "http://barracuda-description.default.svc.cluster.local:11311"
            - name: ROS_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          tty: true
          securityContext:
            privileged: false
      restartPolicy: Always
