apiVersion: apps/v1
kind: Deployment
metadata:
  name: barracuda-manipulation
  labels:
    app: barracuda-manipulation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: barracuda-manipulation
  template:
    metadata:
      labels:
        app: barracuda-manipulation
    spec:
      nodeSelector:
        kubefamily: raspberrypi
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: barracuda-manipulation
          image: ghcr.io/usc-robosub/barracuda-manipulation:latest
          imagePullPolicy: Always
          command: ["/bin/bash", "/opt/barracuda-manipulator/entrypoint.sh"]
          env:
            - name: ROS_MASTER_URI
              value: "http://barracuda-description.default.svc.cluster.local:11311"
            - name: ROS_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          tty: true
          securityContext:
            privileged: true  # adjust if this container needs device access
      restartPolicy: Always
