apiVersion: apps/v1
kind: Deployment
metadata:
  name: barracuda-dvl
  labels:
    app: barracuda-dvl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: barracuda-dvl
  template:
    metadata:
      labels:
        app: barracuda-dvl
    spec:
      nodeSelector:
        kubefamily: jetson
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: barracuda-dvl
          image: ghcr.io/usc-robosub/barracuda-dvl:latest
          imagePullPolicy: Always
          command: ["/bin/bash", "/opt/barracuda-dvl/entrypoint.sh"]
          env:
            - name: ROS_MASTER_URI
              value: "http://barracuda-description.default.svc.cluster.local:11311"
            - name: ROS_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          tty: true
          securityContext:
            privileged: true  # assuming device access is needed
      restartPolicy: Always
