apiVersion: apps/v1
kind: Deployment
metadata:
  name: barracuda-vision
  labels:
    app: barracuda-vision
spec:
  replicas: 1
  selector:
    matchLabels:
      app: barracuda-vision
  template:
    metadata:
      labels:
        app: barracuda-vision
    spec:
      nodeSelector:
        kubefamily: jetson
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: barracuda-vision
          image: barracuda-vision-barracuda-vision:latest
          imagePullPolicy: Never
          command: ["/bin/bash", "/opt/barracuda-vision/entrypoint.sh"]
          env:
            - name: ROS_MASTER_URI
              value: "http://barracuda-description.default.svc.cluster.local:11311"
            - name: ROS_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          tty: true
          securityContext:
            privileged: false
      restartPolicy: Always
