apiVersion: apps/v1
kind: Deployment
metadata:
  name: barracuda-description
  labels:
    app: barracuda-description
spec:
  replicas: 1
  selector:
    matchLabels:
      app: barracuda-description
  template:
    metadata:
      labels:
        app: barracuda-description
    spec:
      nodeSelector:
        kubefamily: jetson
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: barracuda-description
          image: ghcr.io/usc-robosub/barracuda-description:latest
          command: ["/bin/bash", "/opt/barracuda-description/entrypoint.sh"]
          env:
            - name: ROS_MASTER_URI
              value: "http://192.168.2.1:11311"
            - name: ROS_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          tty: true
          securityContext:
            privileged: true
          volumeMounts:
            - name: shared-memory
              mountPath: /dev/shm
      volumes:
        - name: shared-memory
          emptyDir:
            medium: Memory
