apiVersion: v1
kind: Service
metadata:
  name: barracuda-description-service
spec:
  selector:
    app: barracuda-description
  ports:
    - protocol: TCP
      port: 11311
      targetPort: 11311
  clusterIP: None  # Headless service for direct pod-to-pod communication
