apiVersion: v1
kind: Service
metadata:
  name: barracuda-description
  labels:
    app: barracuda-description
spec:
  selector:
    app: barracuda-description
  ports:
    - protocol: TCP
      port: 11311
      targetPort: 11311
  type: ClusterIP
