apiVersion: apps/v1
kind: Deployment
metadata:
  name: barracuda-camera
  labels:
    app: barracuda-camera
spec:
  replicas: 1
  selector:
    matchLabels:
      app: barracuda-camera
  template:
    metadata:
      labels:
        app: barracuda-camera
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: barracuda-camera
          image: ghcr.io/usc-robosub/barracuda-camera:nightly
          command: ["/bin/bash", "/opt/barracuda-camera/entrypoint.sh"]
          env:
            - name: ROS_MASTER_URI
              value: "http://barracuda-description.default.svc.cluster.local:11311"
            - name: ROS_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          tty: true
          securityContext:
            runAsUser: 0
      restartPolicy: Always
