apiVersion: apps/v1
kind: Deployment
metadata:
  name: barracuda-localization
  labels:
    app: barracuda-localization
spec:
  replicas: 1
  selector:
    matchLabels:
      app: barracuda-localization
  template:
    metadata:
      labels:
        app: barracuda-localization
    spec:
      nodeSelector:
        kubefamily: jetson
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: barracuda-localization
          image: barracuda-localization-barracuda-localization:latest
          imagePullPolicy: Never
          command: ["/bin/bash", "/opt/barracuda-localization/entrypoint.sh"]
          env:
            - name: ROS_MASTER_URI
              value: "http://barracuda-description.default.svc.cluster.local:11311"
            - name: ROS_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          tty: true
          securityContext:
            runAsUser: 0
      restartPolicy: Always
