apiVersion: apps/v1
kind: Deployment
metadata:
  name: barracuda-imu
  labels:
    app: barracuda-imu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: barracuda-imu
  template:
    metadata:
      labels:
        app: barracuda-imu
    spec:
      nodeSelector:
        kubefamily: jetson
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: barracuda-imu
          image: barracuda-imu-barracuda-imu:latest
          imagePullPolicy: Never
          command: ["/bin/bash", "/opt/barracuda-imu/entrypoint.sh"]
          env:
            - name: ROS_MASTER_URI
              value: "http://barracuda-description.default.svc.cluster.local:11311"
            - name: ROS_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          tty: true
          securityContext:
            privileged: true
      restartPolicy: Always
